apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-slask
  annotations:
    github.com/project-slug: bjuvensjo/backstage-slask
spec:
  type: other
  lifecycle: unknown
  owner: guests
