# Define the first entity: a Component
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-slask
  annotations:
    github.com/project-slug: bjuvensjo/backstage-slask
spec:
  type: other
  lifecycle: unknown
  owner: guests

# Define the second entity: API for managing user data
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: user-management-api
  description: API for managing user data in our platform.
  owner: guests
  tags:
    - rest
    - user-management
  annotations:
    github.com/project-slug: my-org/user-management-api
spec:
  type: openapi
  lifecycle: production
  owner: user:bjuvensjo 

# Define the third entity: API for product catalog data
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: product-catalog-api
  description: GraphQL API for accessing product catalog data.
  owner: guests
  tags:
    - graphql
    - product
  annotations:
    github.com/project-slug: my-org/product-catalog-api
spec:
  type: graphql
  lifecycle: production
  owner: user:bjuvensjo
