# Define the first entity: a Component
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-slask1
  annotations:
    github.com/project-slug: bjuvensjo/backstage-slask
spec:
  type: other
  lifecycle: live
  owner: guests

# Define the second entity: a Component
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-slask2
  annotations:
    github.com/project-slug: bjuvensjo/backstage-slask
spec:
  type: other
  lifecycle: live
  owner: guests

