apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: baz
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: guests
  system: examples
  definition:
    $text: hhttps://github.com/bjuvensjo/backstage-slask/blob/main/api/baz-api.yaml
